### PR TITLE
remove debug messages

### LINKED ISSUE #8: A lot of debug messages are displayed on the console during tests
Would it possible to silent debug messages when you use BotMock with a testing framework like mocha?

### PR DESCRIPTION
**Pull request by arreche**
End users can use `console.log()` in their tests.

closes #8

### CODE REVIEW

**Comment by chaiwa-berian** [comment]
Yes, I see they are logging every message with isAssertion set to true (in botMock.js) which clutters the output and makes it difficult to view the test results!

**Comment by tansaku** [comment]
[winston](https://github.com/winstonjs/winston) seems like a pretty good controllable logger

**Comment by arreche** [comment]
winston is already used in [BotKit](https://github.com/howdyai/botkit/blob/master/package.json) and perhaps you could also use it from BotMock.

```javascript
var controller = Botkit.slackbot({
  debug: false
  //include "log: false" to disable logging
  //or a "logLevel" integer from 0 to 7 to adjust logging verbosity
});
```

```javascript
botkit.log('[Start] ', task.id, ' Task for ', message.user, 'in', message.channel);
```

https://github.com/howdyai/botkit/blob/aa15b43ed65323fbfabdc797c9f72d8ba1e5754c/lib/CoreBot.js#L1052

Meanwhile, I would be pleased if you just remove those console logs for now ;)

**Comment by ihorrusi** [comment]
it's cool. but these simple `console.log` can help to see what is coming on in `detailedAnswers`.

**Comment by tansaku** [comment]
thanks @ihorrusi they can be very useful, but we need a mechanism to easily turn them on and off :-)

**Pull request merged**
